# Generated by Django 5.1.3 on 2024-11-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('music_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='music.musicfile')),
            ],
        ),
    ]
