# Generated by Django 5.0.7 on 2024-10-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_musicfile_report"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MusicFile",
        ),
    ]
