# Generated by Django 5.0.7 on 2024-10-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_musicfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
