# Generated by Django 5.0.7 on 2024-10-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicfile",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
