# Generated by Django 5.0.7 on 2024-10-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_musicfile_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicfile",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
