# Generated by Django 5.0.7 on 2024-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_musicfile_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicfile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="musicfile",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
