# Generated by Django 5.0.7 on 2024-10-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_musicfile_file_name_alter_musicfile_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musicfile",
            old_name="file",
            new_name="file_path",
        ),
    ]
